# docker-compose.yml

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: modular_dashboard_api
    env_file:
      - ./backend/.env # API loads variables from here
    # --- ADICIONADO environment com PYTHONPATH ---
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # Mount entire backend to /app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: pgvector/pgvector:pg16
    container_name: modular_dashboard_db
    env_file:
      - ./backend/.env # DB service now relies solely on this file for POSTGRES_* vars
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-appuser} -d $${POSTGRES_DB:-appdb}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge