# backend/app/modules/ai_test/v1/schemas.py
from pydantic import BaseModel, Field

class TextInput(BaseModel):
    """Schema for text input to the AI model."""
    text: str = Field(..., description="The input text prompt for the AI model.")
    # Add other input fields later if needed

class AIResponse(BaseModel):
    """Schema for the response received from the AI model."""
    response: str = Field(..., description="The text response generated by the AI model.")